name: Publicar reporte de cobertura

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore & Test con cobertura
        working-directory: MyMath             # <— aquí
        run: |
          dotnet restore                      # ahora restaurará MyMath/MyMath.sln
          dotnet test --collect:"XPlat Code Coverage"

      - name: Instalar ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generar reporte HTML
        working-directory: MyMath             # <— y aquí
        run: reportgenerator \
          "-reports:**/coverage.cobertura.xml" \
          "-targetdir:Cobertura" \
          -reporttypes:HTML

      - name: Desplegar reporte de cobertura
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: coverage-pages
          publish_dir: MyMath/Cobertura       # <— apunta a donde realmente genera la carpeta
